// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveNormal.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveNormal::DriveNormal(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveNormal::Initialize() {
	Robot::drive->DriveMethod(0,0);
}

// Called repeatedly when this Command is scheduled to run
void DriveNormal::Execute() {
	Robot::drive->DriveMethod(Robot::oi->GetDriveY(), Robot::oi->GetDriveX());
	SmartDashboard::PutNumber("Drive Value", Robot::oi->GetDriveY());
	SmartDashboard::PutString("drivenormal","yeah");
	//Robot::drive->DriveMethod(Robot::oi->getDriveJoy()->GetY(),Robot::oi->getDriveJoy()->GetX());
}

// Make this return true when this Command no longer needs to run execute()
bool DriveNormal::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveNormal::End() {
	Robot::drive->DriveMethod(0,0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveNormal::Interrupted() {
	Robot::drive->DriveMethod(0,0);
}
